### ISSUE TITLE
python 3.5.1 and python-bioformats

### ISSUE THREAD

**Issue by kraftlj** [CellProfiler/python-bioformats#51] opened 2016-03-25 02:15 UTC
Hi,

I recently installed python-bioformats, but I got the following error using Python 3.5.1 :: Anaconda 2.5.0 (64-bit) on `import bioformats`

python : Traceback (most recent call last):
At line:1 char:1
- python temp.py 2> output.txt
- ```
  ```
  - CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError
  
  File "temp.py", line 3, in <module>
    import bioformats
  File "C:\Users\kraftlj\Anaconda3\lib\site-packages\python_bioformats-0.0.0-py3.5.egg\bioformats__init__.py", line 
  20, in <module>
  from . import formatreader as _formatreader
  File "C:\Users\kraftlj\Anaconda3\lib\site-packages\python_bioformats-0.0.0-py3.5.egg\bioformats\formatreader.py", 
  line 450
  __omero_server, __omero_port, __omero_username, __omero_password]):
                ^
  SyntaxError: invalid syntax

**Comment by LeeKamentsky** [comment] 2016-03-25 12:19
It's a duplicate of issue #12. Sorry about that - no Python 3 support yet, you can track any progress there. Until it's fixed, only Python 2.7 is supported.

**Comment by alimuldal** [comment] 2016-03-30 13:16
I've just opened a pull request that adds Python3 support: #52

**Comment by mcquin** [comment] 2017-08-18 14:49
Closed as duplicate.

**Closed by mcquin** 2017-08-18 14:49 UTC
