### ISSUE TITLE
AttributeError: 'ImageReader' object has no attribute 'rdr'

### ISSUE THREAD

**Issue by tangji0318** [CellProfiler/python-bioformats#25] opened 2015-05-09 06:28 UTC
Dear Mr. Kamentsky,
I encountered an error when running my python with bioformats:

jmd = jv.JWrapper(rdr.rdr.getMetadataStore())
AttributeError: 'ImageReader' object has no attribute 'rdr'

I could find ImageReader class in formatreader.py under the folder \site-packages\bioformats, but no attribute 'rdr' there.
If I ran it in command line, I got error as follows:

File "C:\Program Files\Anaconda\Lib\site-packages\javabridge\wrappers.py", line 81, in __getattr__
raise AttributeError()

If I run test macro as follows:

import os
import javabridge as jv
paths = jv.JClassWrapper('java.lang.System').getProperty('java.class.path').split(";")
for path in paths:
    print "%s: %s" %("exists" if os.path.isfile(path) else "missing", path)

I can get:

exists: C:\Program Files\Anaconda\lib\site-packages\javabridge\jars\rhino-1.7R4.jar
exists: C:\Program Files\Anaconda\lib\site-packages\javabridge\jars\runnablequeue.jar
exists: C:\Program Files\Anaconda\lib\site-packages\javabridge\jars\cpython.jar
exists: C:\Users\zcjitang\Documents\Software\Bioformats\bioformats_package_5.1.1.jar

Then I do not know what's wrong with it. Could you help? Thank you very much.
I had installed the latest PyWin32, Bioformats, Javabridge, vLFD, Numpy and matplotlib based on my requirements from http://www.lfd.uci.edu/~gohlke/pythonlibs/.

**Comment by LeeKamentsky** [comment] 2015-05-11 12:27
Hi,
Could you post a short stand-alone script that shows the complete problem? Also, I'm not sure which version Christoph is using for his distribution, could you also `print bioformats.__version__`?

Here's a short script that works for me using the most recently committed code.

    import javabridge
    import bioformats
    print bioformats.__version__
    javabridge.start_vm(class_path=bioformats.JARS)
    rdr = bioformats.get_image_reader(None, path="c:/trunk/ExampleImages/ExampleSBSImages/Channel1-01-A-01.tif")
    metadata = javabridge.JWrapper(rdr.rdr.getMetadataStore())
    print metadata.getChannelCount(0)

Output:

    1.0.4-3-g84a1835
    1

**Comment by tangji0318** [comment] 2015-05-12 16:38
Dear Mr. Kamentsky,
Thanks for your reply. Just for your code, I can get correct output for my .png file, but not for my .czi file from ZEISS. When I read one .czi file, I get error like this:

File "C:\Program Files\Anaconda\lib\site-packages\bioformats\formatreader.py", line 723, in init_reader
raise e2
IOError: [Errno 22] Could not load the file as an image (see log for details):

If I print my bioformats version with print bioformats.__version__, I get "1.0.4", just as the version I installed. Thanks!

Ji
May 13, 2015

**Comment by LeeKamentsky** [comment] 2015-05-12 16:59
It might be a problem with Bio-formats itself. You can test it out like this:

* Find the bioformats package directory:

    `python -c "import bioformats;import os;print os.path.join(os.path.dir
name(bioformats.__file__), 'jars')"`

* CD to that directory and run the loci_tools.jar as an application

    `java -jar loci_tools.jar`

* Use the UI to load your file.

If the file doesn't load using loci_tools.jar directly, it's a Bio-formats problem. You should download the latest bioformats_package.jar from them and launch it using java-jar bioformats_package.jar and try your file. If it still doesn't work, you should contact them. If it does work, you can start up the Javabridge like this:

    javabridge.start_vm(class_path = javabridge.JARS + [path-to-bioformats_package.jar])

If loci_tools can load your file but python-bioformats can't, please post the console error output and, if possible, send me the file itself.

**Comment by tangji0318** [comment] 2015-05-13 08:32
Dear Mr. Kamentsky,
Thanks for your detailed reply. I cannot use that UI to load my .czi file (.png file is OK). Then I upgrade my python-bioformats in the Anaconda command line:

pip install --upgrade python-bioformats

However, it still fails . I intended to upload my .czi file, but it fails with error "we don't support that file type". Is it possible that my latest bioformats is 1.0.4, not your 1.0.4-3-g84a1835? If so, how could I get that version?
Thanks.

Ji
May 13, 2015

**Comment by LeeKamentsky** [comment] 2015-05-13 12:39
If I understand you correctly, you used the command:

    java -jar loci_tools.jar

to start the bioformats UI and tried, unsuccessfully to load your.czi file. If so, the problem isn't with python-bioformats, it's with bioformats itself. Upgrading python-bioformats won't help - you need to post the output that appears on your console here at least and preferably send me the .czi file itself so I can diagnose further. Since it's almost surely a Bioformats problem, the proper course of action is to follow the instructions on this page:

http://www.openmicroscopy.org/site/support/bio-formats5.1/about/bug-reporting.html

I would recommend following those instructions. If you download the latest copy of bioformats_package.jar according to those directions, run `java -jar bioformats_package.jar` and succeed in reading your file, then we can continue here, otherwise the best course of action is to go through their bug reporting procedure and CC me (leek@broadinstitute.org).

**Comment by tangji0318** [comment] 2015-05-15 06:15
Dear Mr. Kamentsky,
Thanks for your reply. I've reported the problem to OME Users and cc to you. You can also find the original file and error screenshot.
Thanks again.

Ji
May 15, 2015

**Comment by LeeKamentsky** [comment] 2015-05-15 16:38
It looks like there's an additional problem - rdr.isIndexed() returns True, indicating that the .czi file has to be run through a color index table, but the table is not present. This causes bioformats to get the table, which is null / None and then it calls the low-level and unsafe, JB_Env.get_short_array_elements with the null pointer. :boom:.

Needs a fix to check for null and then cast the image as monochrome.

**Comment by LeeKamentsky** [comment] 2015-05-15 17:15
I've successfully read the image using python-bioformats 1.0.5 (I just released it on pypi - `pip install --upgrade --no-deps python-bioformats` to upgrade to 1.0.5. 1.0.5 is using BioFormats 5.0.6 which is able to read your image.
![image](https://cloud.githubusercontent.com/assets/660469/7657993/74662a60-fb04-11e4-824f-ebb121238c7c.png)

**Closed by LeeKamentsky** 2015-05-15 17:15 UTC

**Comment by tangji0318** [comment] 2015-05-17 04:11
Dear Mr. Kamentsky,
Thanks for your help. I've upgraded my python-bioformats to 1.0.5 version. However, it does not work for me.
When I run "java -jar loci_tools.jar", I got this:
![image](https://cloud.githubusercontent.com/assets/12229603/7668970/631fc05c-fc8c-11e4-8a92-2f6f9d69de5d.png)
When I run "java -jar bioformats_package_5.1.1.jar", I got one 2-T and 2-Z image. However, it;s a 1-T and 1-Z image.
What's wrong with it? Thanks.

Ji
May 17, 2015

**Comment by tangji0318** [comment] 2015-05-17 04:43
Dear Mr. Kamentsky,
I'm sorry that I made a mistake. Now I can get 1-T and 1-Z image with both methods. The only problem is that it shows like a 16-bit image.
Thanks.

Ji
May 17, 2015

**Comment by emmanuel-contreras** [comment] 2019-03-28 17:26
hello, I'm running into this problem as well and can't seem to get it to work while trying to load an sdt file. 

Should I start a new thread? It is the same error AttributeError: 'ImageReader' object has no attribute 'rdr'

bioformats.load_image(path) loads the image fine. loci_tools.jar loads it fine, but trying to use the bioformats.get_image-reader function gives me the error. I tried using the reader a couple of ways and the code below gives me the following error. 

  File "C:\ProgramData\Anaconda3\lib\site-packages\bioformats\formatreader.py", line 787, in read
    openBytes_func = self.rdr.openBytes

```language=python
with bioformats.get_image_reader(None,file) as reader:
    print(reader.read(t=100))
    #print(reader.rdr.getSizeX())
```

Thank you
